spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: share_my_hobby
  redis:
    host: 127.0.0.1
    port: 6379
cloud:
  aws:
    region:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucketName: share-my-hobby
    stack:
      auto: false
server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
kakao:
  restapi:
    key:

--- ## develop
spring:
  profiles: develop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/f-lab?autoreconnect=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password:

--- ## local
spring:
  profiles: local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/f-lab?autoreconnect=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password:

--- ## test
spring:
  profiles: test
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_sharemyhobby;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    pool-name: TEST_H2_DB
    schema: classpath*:sql/schema.sql